### ISSUE TITLE
Перенос аргументов в длинной строке 

### ISSUE THREAD

**Issue by vani2** [RedMadRobot/RMR-swift-style-guide#1]
Мне кажется, что в таких случаях, когда первый аргумент выходит за границы guide-линии, перенос первого аргумента нужно делать обязательно. 
![2](https://cloud.githubusercontent.com/assets/4734983/17616620/fe9a548e-6086-11e6-9af4-73e06f6d08ec.png)

![1](https://cloud.githubusercontent.com/assets/4734983/17616619/fe6d87e2-6086-11e6-962c-f2c758f5962c.png)

По умолчанию проголосовали, что перенос параметров на новую строку начиная со второго.

**Comment by firmach** [comment]
И как будем решать? 🙂

**Comment by vani2** [comment]
> когда первый аргумент выходит за границы guide-линии, перенос первого аргумента нужно делать обязательно. 

@antonypoderechin  @firmach так норм?

**Comment by eugeneego** [comment]
У нас (СПб) никакая строка не должна выходить за настроенные пределы.
SwiftLint настроен и генерит ворнинги при приближении и ошибки при выходе за пределы.
Переносим несколькими вариантами в зависимости от ситуации:

``` swift
let res1 = someFunction(parameter1: "value1", parameter2: "value2",
    parameter3: "value3", parameter4: "value4", parameter5: "value5")

let res2 = someFunction(
    parameter: "value1",
    anotherParameter: "value2",
    parameter: "value3",
    parameter4: "value4",
    completion: { param in
        // ...
    }
)
```

**Comment by antonypoderechin** [comment]
+1 за по ситуации

**Comment by Hardenn** [comment]
Мне нравится СПбшная идея с пределами, я ее и так стараюсь придерживаться, так что по-моему отличный вариант с переносом первого аргумента, если ситуация такая.

**Comment by firmach** [comment]
Супер! Все заинтересованные высказались?

**Comment by antonypoderechin** [comment]
Я думаю если бы кто то был против, он бы высказался ;-)
