### ISSUE TITLE
Не согласна: Leave two empty lines between functions

### ISSUE THREAD

**Issue by Hardenn** [RedMadRobot/RMR-swift-style-guide#2]
По-моему одной пустой строки между методами достаточно, чтобы они нормально читались. Лишние строки визуально зашумляют.

Коммит: c018cac7fb01eda6ae23e963a03bc86fb6ff1951

**Comment by vani2** [comment]
Нет, мне как раз сложно читать, потому что в методе могут быть пустые строки и не понимаешь – это пустая строка между функциями или внутри неё.

**Comment by firmach** [comment]
Если между функциями будет две пустые строки, то уж между MARK'ами точно надо как минимум три.

**Comment by Hardenn** [comment]
Обсудили с Ваней, две строки ок. Три между марками ставить — очень просторный файл выходит :) Закрою issue по поводу двух строк
