### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by Hardenn** [RedMadRobot/RMR-swift-style-guide#3]
// MARK: - Public Properties
// MARK: - Private Properties

Зачем их делить? Зашумление по-моему

// MARK: - ViewController Life Cycle

Мб просто Life cycle? Так короче, а во вьюхах не надо отдельно View Life Cycle писать

// MARK: - IBAction

Мб Actions? Иногда туда попадают приватные методы, которые мы пишем в селекторы.

Коммит: 26b53760a18800b29e0984a267570128c27a0b21

**Comment by vani2** [comment]
> Зачем их делить? Зашумление по-моему

Чтобы не писали
```swift
let var1
private let var2
let var3
private var4

```

**Comment by Hardenn** [comment]
Ну тогда уже нужно правило в каком порядке объявлять:

`let var1`
`let var3`
`private let var2`
`private var4`

**Comment by vani2** [comment]
Не проще ориентироваться, когда `MARK` уже есть?

**Comment by firmach** [comment]
Я согласен с
// MARK: - Public Properties
// MARK: - Private Properties

И думаю, что надо писать просто
// MARK: - Actions

А еще я за то чтобы убрать "-" из наших MARK. ИМХО его надо применять по случаю.

**Comment by vani2** [comment]
Мне как раз с ними легче, потому что могут быть всякие `TODO` и `FIXME`, которые без сепаратора.

**Comment by Hardenn** [comment]
Уговорили на

// MARK: - Public Properties
// MARK: - Private Properties
