### ISSUE TITLE
Перенос if else и переменных

### ISSUE THREAD

**Issue by SergeyCHiP** [RedMadRobot/RMR-swift-style-guide#4]
Уже ни раз топил про if else...

1) если всё просто и всего несколько строк то для краткости использую 

```
if user.isHappy {
  // Do something
} else {
  // Do something else
}

```

2) Если несколько несколькострочных блоков то **else** переносится на новую строчку (удобно сворачивать блоки кода, удобно переносить если несколько let переменных):

![presentationmodel swift__edited_2017-08-30_10-31-56](https://user-images.githubusercontent.com/2941633/29860355-8c9bbc72-8d6e-11e7-9e08-94e406407648.png)

p.s. можно сказать что в текущем коде лучше switch, но сейчас не об этом =) 

3) Если несколько let переменных, то в if переносятся все на новую строку:

```
if 
   let someV = someV,
   let someB = someV.someB {

       someV.x + someB.y
}
```

**Comment by vani2** [comment]
1-2 не вижу особой разницы, но на большинстве наших проектов и apple используются переносы в стиле K&R. Здесь правильнее встать на их сторону.
3 – можно, так получше.

**Comment by Hardenn** [comment]
1-2 согласна с Ваней, лучше оставить один стиль переноса else
3 — согласна, можно

**Comment by SergeyCHiP** [comment]
Просто у нас часто встречается, когда кол-во условий зашкаливает, а это совсем не по K&R.
Стоит тогда не только переносы правильно писать, но и в целом условия.

**Comment by vani2** [comment]
Оставляем как есть, неправильно из-за сворачивания менять переносы. Про несколько `if let` добавлю.
