### ISSUE TITLE
Функции

### ISSUE THREAD

**Issue by SergeyCHiP** [RedMadRobot/RMR-swift-style-guide#6]
1) Такие методы как по мне сложно читать, не понятно где начало кода. Почему бы не добавлять пустую строку?
**from**
```
func reticulateSplines(
    spline: [Double], 
    adjustmentFactor: Double,
    translateConstant: Int, 
    comment: String) -> Bool {
  // reticulate code goes here
}
```
**to**
```
func reticulateSplines(
    spline: [Double], 
    adjustmentFactor: Double,
    translateConstant: Int, 
    comment: String) -> Bool {

  // reticulate code goes here
}
```

2) Иногда методы (особенное фабричные, или делегатов) отличаются возвращаемой переменной, в таких случаях удобно читать, если **-> SomeClass** переносится на новую строку (глазами не отвлекаешься на набор параметров, а ищешь нужный класс):
```
func reticulateSplines(spline: [Double],  comment: String) 
    -> Bool {

          // reticulate code goes here
}
```
![organizationrouter swift__edited_2017-08-30_10-54-04](https://user-images.githubusercontent.com/2941633/29861323-93af8428-8d71-11e7-8b4d-25aad942cdb3.png)

**Comment by vani2** [comment]
1 – думаю, можно.
2 – не согласен. При page guide 90 символов кмк компактно смотрится. Если в 90 не влазит, то переносишь.

**Comment by Hardenn** [comment]
1 — согласна
2 — наверное выглядит хорошо, если схлопнуть body метода, в остальном тоже смысла не вижу

**Comment by firmach** [comment]
1 — омерзительно!
2 — пофиг

--
С уважением,
Роман Чуркин, Lead iOS Engineer

REDMADROBOT | www.redmadrobot.ru

**Comment by SergeyCHiP** [comment]
≥≥ 2 – не согласен. При page guide 90 символов кмк компактно смотрится. Если в 90 не влазит, то переносишь.

так я и пишу "Иногда" вот 90 норм правило...

**Comment by vani2** [comment]
Давайте по этой штуке договоримся, не понимаю кому как удобно @SergeyCHiP @Hardenn @firmach @zhorkov023

**Comment by firmach** [comment]
Я всё еще против пустой строки — меня от зебры укачивает 🤣 
Возвращаемый параметр я не против переносить, если не влазит. Правда там обычно не влезет из-за параметров и если их перенести, то начинает влазить...

**Comment by Hardenn** [comment]
Пустую строку наверное можно оставить по вкусовщине. Я бы ставила ее для читаемости, Рома нет. Мб будем делать, кому как нравится? Это вроде мелочь.

Возвращаемый параметр не придется переносить, если перенесутся параметры. Согласна с Ромой, по идее не пригодится, а глаз останавливается с непривычки.

**Comment by SergeyCHiP** [comment]
всё сливается и непонятно где код, а где параметры.

**Comment by taflanidi** [comment]
@SergeyCHiP, @vani2, @Hardenn, @firmach, у меня для вас есть пара мыслей вслух на заметку.

### Сигнатура метода получается слишком «концентрированной»:
```swift
func foo(
    parameter: String,
    count: Int) -> Bar { // вот тут происходит дохрена всего: параметры, результат, скобки, стрелки
    
    // требуется пустая строка
}
```
### Вы используете египетские скобки:
![Image](https://lehacker.com/wp-content/uploads/2017/01/egyptian-brackets-programming-jargon.jpg)
Смысл этих скобок — обозначить **рамки**. 

### Идея:
Использовать египетские скобки для обозначения рамок **везде**.
Рамки параметров:
```swift
... ... (                           // параметры начались
    parameter: String,
    count: Int
)                                   // параметры кончились
```
Рамки тела метода:
```swift
... ... {                           // тело началось
    return Bar()
}                                   // тело кончилось
```
Всё вместе — по аналогии с if + else (например):
```swift
if condition {
    // scope 1
} else {
    // scope 2
}


func foo(                             //    if condition {
    parameter: String                 //        scope 1
) -> Bar {                            //    } else {
    return Bar()                      //        scope 2
}                                     //    }
```

Для меня иногда бывает важно иметь простое логическое обоснование даже для элементарных поступков и решений. Возможно, такое логическое обоснование кому-нибудь из вас придётся по душе. Мол, есть scope для тела, есть scope для аргументов, оба они обозначаются одинаково.

Да, это означает, что для процедур, которые ничего не возвращают, будет так:
```swift
func foo(
    parameter: String,
    count: Int
) {    
    // return nothing
}
```
А для вызовов c большим количеством параметров так:
```swift
bar(parameter: String)           //    if condition { scope 1 }


foo(                             //    if condition {
    parameter: String,           //        scope 1
    parameter2: String,          //
    parameter3: String,          //
    parameter4: String           //
)                                //    } 


return Optional.none
```

**Comment by Hardenn** [comment]
@taflanidi Звучит вроде логично, но выглядит страшно :(
