### ISSUE TITLE
ViewController Life Cycle и Types

### ISSUE THREAD

**Issue by m-konovalov** [RedMadRobot/RMR-swift-style-guide#7]
+ Предлагаю вместо:

`// MARK: - ViewController Life Cycle`

использовать:

`// MARK: - UIViewController //<Имя класса, чьи методы оверрайдишь>`

Так у нас будет одно поведение для всех классов-наследников, и можно будет оверрайдить в этом марке методы контроллера, которые не относятся к его жизненному циклу.

+ Добавить 

`// MARK: - Types `

для вложенных типов

**Comment by Hardenn** [comment]
В смысле под таким марком оверрайдим и методы жизненного цикла, и методы базового класса типа обработки ошибок?

**Comment by m-konovalov** [comment]
Ну я предлагаю в целом ввести такую марку, где мы оверрайдим методы базового класса. ViewController Life Cycle попадает под эту марку, поэтому отдельное выделение жизненного цикла я думаю что избыточно.

**Comment by m-konovalov** [comment]
+ предлагаю добавить 

`// MARK: - Types `

для вложенных типов

**Comment by Hardenn** [comment]
Я не против

**Comment by vani2** [comment]
Хорошо, добавлю.
